#!/bin/ksh

# relayd_archive - Archive a copy of the relayd service under OpenBSD

service="relayd"
set -A src "/etc/relayd.conf" "/etc/services" "/etc/ssl"
dst="${1:-/var/backups/${service}}"

host="$(hostname)"
tool="$(basename "$0")"
date="$(date +%Y%m%d-%H%M%S)"

if [ ! -d "$dst" ]; then
  echo "ERROR: Destination '${dst}' doesn't exist!"
  echo "Exiting."
  exit 1
fi
tar czvf "${dst}/${host}-${service}-${date}.tar.gz" "$0" "${src[@]}"
